# =========================
# Site settings
# =========================
title: alface0x19
name: alface0x19
description: Blog técnico • Segurança • DevOps • Write-ups
url: https://alface0x19.github.io
baseurl: ""

# =========================
# Theme (Dark)
# =========================
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

# =========================
# Build settings
# =========================
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# =========================
# Plugins (GitHub Pages OK)
# =========================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# =========================
# Author
# =========================
author:
  name: alface0x19
  bio: "Cybersecurity • DevOps • CTFs"
  location: Portugal
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/alface0x19
    - label: YouTube
      icon: fab fa-youtube
      url: https://www.youtube.com/@alface0x19

# =========================
# Defaults
# =========================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true

# =========================
# Navigation
# =========================
header_pages:
  - index.md
  - support.md

# =========================
# Excludes
# =========================
exclude:
  - README.md
